version: "3.8"

networks:
  nginx-php74-mysql8-node:
    driver: bridge

services:
  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - mysql8-service
    networks:
      - nginx-php74-mysql8-node

  # php
  php74-service:
    image: php:7.4-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php74-container
    ports:
      - "9000:9000"
    volumes:
      - /Users/racheal/code/product-api:/var/www/project
    depends_on:
      - mysql8-service
    networks:
      - nginx-php74-mysql8-node

  # mysql
  mysql8-service:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: product-api
      MYSQL_USER: root
      MYSQL_PASSWORD: secret123
    networks:
      - nginx-php74-mysql8-node
