name: PHPUnit tests, PHP_CodeSniffer, and PHPStan analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: secret123
          MYSQL_DATABASE: product-api-test
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker containers
        run: docker-compose up --build -d

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.0
          extensions: mbstring, intl, pdo_mysql

      - name: Run Doctrine Migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

      - name: Run PHPStan
        run: php -d memory_limit=256M vendor/bin/phpstan analyse

      - name: Upload PHPUnit coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload PHPStan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phpstan-report
          path: phpstan_results.txt
