name: PHPUnit tests, PHP_CodeSniffer, and PHPStan analysis.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, pdo_mysql

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=ruleset.xml src/

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --configuration=phpstan.dist.neon

      - name: Upload PHPUnit coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload PHPStan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phpstan-report
          path: phpstan.dist.neon
