name: PHPUnit tests, PHP_CodeSniffer, and PHPStan analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  services:
    mysql:
    image: mysql:5.6
    env:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: product-api-test
    ports:
      - 3307:3306
    options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

  steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.0
        extensions: mbstring, intl, pdo_mysql

    - name: Install dependencies
      run: bash ci/docker_install.sh

    - name: Run PHPUnit tests
      run: phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Run PHPStan
      run: composer phpstan | tee phpstan_results.txt

    - name: Run security checker
      run: security-checker security:check

    - name: Run washing machine
      run: /root/washingmachine/washingmachine run -v

    - name: Upload PHPUnit coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
          ath: coverage.xml

    - name: Upload PHPStan report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: phpstan-report
        path: phpstan_results.txt

